version: '3'
services:
  webapp1:
    build: .
    ports:
      - '5002:5000'
    volumes:
      - ./:/app/hello_world
    environment:
      - NAME='Nashawn'

  # webapp2:
  #   build: .
  #   ports:
  #     - '5003:5000'
  #   volumes:
  #     - ./:/app/hello_world
  loadbalancer:
    build:
      context: './nginx'
      dockerfile: 'Dockerfile'
    restart: always
    ports:
      - '5001:80'
    depends_on:
      # - webapp2
      - webapp1
