version: '3'
services:
  nginx:
    restart: always
    build:
      context: './nginx'
      dockerfile: 'Dockerfile'
    ports:
      - '3050:80'
  webapp1:
    build: .
    volumes:
      - ./:/app/hello_world
    environment:
      - NAME='Nashawn'
  webapp2:
    build: .
    volumes:
      - ./:/app/hello_world
